#datasource specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospitalmgmt
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true